// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 01 Feb 2017 05:13:32 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int chan_cb_t_2d1ed0bd(RIG* arg0, channel_t** arg1, int arg2, chan_t* arg3, void* arg4) {
	return chanCb2D1ED0BD(arg0, arg1, arg2, arg3, arg4);
}

int confval_cb_t_8d622de4(RIG* arg0, struct confparams* arg1, value_t* arg2, void* arg3) {
	return confvalCb8D622DE4(arg0, arg1, arg2, arg3);
}

int vprintf_cb_t_fddf9323(enum rig_debug_level_e arg0, void* arg1, char* arg2, void* arg3) {
	return vprintfCbFDDF9323(arg0, arg1, arg2, arg3);
}

int freq_cb_t_8c3d2c4c(RIG* arg0, int arg1, double arg2, void* arg3) {
	return freqCb8C3D2C4C(arg0, arg1, arg2, arg3);
}

int mode_cb_t_d7e6dd52(RIG* arg0, int arg1, rmode_t arg2, long int arg3, void* arg4) {
	return modeCbD7E6DD52(arg0, arg1, arg2, arg3, arg4);
}

int vfo_cb_t_ac116829(RIG* arg0, int arg1, void* arg2) {
	return vfoCbAC116829(arg0, arg1, arg2);
}

int ptt_cb_t_f32e1e11(RIG* arg0, int arg1, ptt_t arg2, void* arg3) {
	return pttCbF32E1E11(arg0, arg1, arg2, arg3);
}

int dcd_cb_t_aa70811b(RIG* arg0, int arg1, dcd_t arg2, void* arg3) {
	return dcdCbAA70811B(arg0, arg1, arg2, arg3);
}

int pltune_cb_t_26f9489a(RIG* arg0, int arg1, double* arg2, rmode_t* arg3, long int* arg4, void* arg5) {
	return pltuneCb26F9489A(arg0, arg1, arg2, arg3, arg4, arg5);
}

int rig_probe_func_t_ce8c6199(hamlib_port_t* arg0, int arg1, void* arg2) {
	return rigProbeFuncCE8C6199(arg0, arg1, arg2);
}

