// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 01 Feb 2017 05:13:32 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

package hamlib

/*
#cgo pkg-config: hamlib
#include "hamlib/rig.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Rignamsiz as defined in hamlib/rig.h:138
	Rignamsiz = 30
	// Rigversiz as defined in hamlib/rig.h:139
	Rigversiz = 8
	// RigFlagTransceiver as defined in hamlib/rig.h:228
	RigFlagTransceiver = 0
	// RigTypeMask as defined in hamlib/rig.h:229
	RigTypeMask = 0
	// RigTypeOther as defined in hamlib/rig.h:231
	RigTypeOther = 0
	// RigTypeTransceiver as defined in hamlib/rig.h:232
	RigTypeTransceiver = RigFlagTransceiver
	// RigTypeHandheld as defined in hamlib/rig.h:233
	RigTypeHandheld = 0
	// RigTypeMobile as defined in hamlib/rig.h:234
	RigTypeMobile = 0
	// RigTypeReceiver as defined in hamlib/rig.h:235
	RigTypeReceiver = 0
	// RigTypePcreceiver as defined in hamlib/rig.h:236
	RigTypePcreceiver = 0
	// RigTypeScanner as defined in hamlib/rig.h:237
	RigTypeScanner = 0
	// RigTypeTrunkscanner as defined in hamlib/rig.h:238
	RigTypeTrunkscanner = 0
	// RigTypeComputer as defined in hamlib/rig.h:239
	RigTypeComputer = 0
	// RigTypeTuner as defined in hamlib/rig.h:240
	RigTypeTuner = 0
	// RigStatusNew as defined in hamlib/rig.h:257
	RigStatusNew = RigStatusUntested
	// RigVfoNone as defined in hamlib/rig.h:324
	RigVfoNone = 0
	// RigVfoTxFlag as defined in hamlib/rig.h:326
	RigVfoTxFlag = (1 << 30)
	// RigVfoCurr as defined in hamlib/rig.h:329
	RigVfoCurr = (1 << 29)
	// RigVfoMem as defined in hamlib/rig.h:332
	RigVfoMem = (1 << 28)
	// RigVfoVfo as defined in hamlib/rig.h:335
	RigVfoVfo = (1 << 27)
	// RigVfoTx as defined in hamlib/rig.h:340
	RigVfoTx = 1610612736
	// RigVfoRx as defined in hamlib/rig.h:343
	RigVfoRx = RigVfoCurr
	// RigVfoMain as defined in hamlib/rig.h:346
	RigVfoMain = (1 << 26)
	// RigVfoSub as defined in hamlib/rig.h:348
	RigVfoSub = (1 << 25)
	// RigVfoA as defined in hamlib/rig.h:353
	RigVfoA = 1
	// RigVfoB as defined in hamlib/rig.h:355
	RigVfoB = 2
	// RigVfoC as defined in hamlib/rig.h:357
	RigVfoC = 4
	// RigTargetableNone as defined in hamlib/rig.h:364
	RigTargetableNone = 0
	// RigTargetableFreq as defined in hamlib/rig.h:365
	RigTargetableFreq = (1 << 0)
	// RigTargetableMode as defined in hamlib/rig.h:366
	RigTargetableMode = (1 << 1)
	// RigTargetablePure as defined in hamlib/rig.h:367
	RigTargetablePure = (1 << 2)
	// RigTargetableTone as defined in hamlib/rig.h:368
	RigTargetableTone = (1 << 3)
	// RigTargetableFunc as defined in hamlib/rig.h:369
	RigTargetableFunc = (1 << 4)
	// RigTargetableAll as defined in hamlib/rig.h:370
	RigTargetableAll = 0x7fffffff
	// RigConfEnd as defined in hamlib/rig.h:510
	RigConfEnd = 0
	// RigComboMax as defined in hamlib/rig.h:534
	RigComboMax = 8
	// RigAntNone as defined in hamlib/rig.h:578
	RigAntNone = 0
	// RigLevelFloatList as defined in hamlib/rig.h:673
	RigLevelFloatList = (RigLevelAf | RigLevelRf | RigLevelSql | RigLevelApf | RigLevelNr | RigLevelPbtIn | RigLevelPbtOut | RigLevelRfpower | RigLevelMicgain | RigLevelComp | RigLevelBalance | RigLevelSwr | RigLevelAlc | RigLevelVoxgain | RigLevelAntivox)
	// RigLevelReadonlyList as defined in hamlib/rig.h:675
	RigLevelReadonlyList = (RigLevelSqlstat | RigLevelSwr | RigLevelAlc | RigLevelStrength | RigLevelRawstr)
	// RigParmFloatList as defined in hamlib/rig.h:700
	RigParmFloatList = (RigParmBacklight | RigParmBat)
	// RigParmReadonlyList as defined in hamlib/rig.h:701
	RigParmReadonlyList = (RigParmBat)
	// RigSettingMax as defined in hamlib/rig.h:706
	RigSettingMax = 32
	// RigTrnOff as defined in hamlib/rig.h:719
	RigTrnOff = 0
	// RigTrnRig as defined in hamlib/rig.h:720
	RigTrnRig = 1
	// RigTrnPoll as defined in hamlib/rig.h:721
	RigTrnPoll = 2
	// RigFuncNone as defined in hamlib/rig.h:741
	RigFuncNone = 0
	// RigFuncFagc as defined in hamlib/rig.h:742
	RigFuncFagc = (uint64(1) << 0)
	// RigFuncNb as defined in hamlib/rig.h:743
	RigFuncNb = (uint64(1) << 1)
	// RigFuncComp as defined in hamlib/rig.h:744
	RigFuncComp = (uint64(1) << 2)
	// RigFuncVox as defined in hamlib/rig.h:745
	RigFuncVox = (uint64(1) << 3)
	// RigFuncTone as defined in hamlib/rig.h:746
	RigFuncTone = (uint64(1) << 4)
	// RigFuncTsql as defined in hamlib/rig.h:747
	RigFuncTsql = (uint64(1) << 5)
	// RigFuncSbkin as defined in hamlib/rig.h:748
	RigFuncSbkin = (uint64(1) << 6)
	// RigFuncFbkin as defined in hamlib/rig.h:749
	RigFuncFbkin = (uint64(1) << 7)
	// RigFuncAnf as defined in hamlib/rig.h:750
	RigFuncAnf = (uint64(1) << 8)
	// RigFuncNr as defined in hamlib/rig.h:751
	RigFuncNr = (uint64(1) << 9)
	// RigFuncAip as defined in hamlib/rig.h:752
	RigFuncAip = (uint64(1) << 10)
	// RigFuncApf as defined in hamlib/rig.h:753
	RigFuncApf = (uint64(1) << 11)
	// RigFuncMon as defined in hamlib/rig.h:754
	RigFuncMon = (uint64(1) << 12)
	// RigFuncMn as defined in hamlib/rig.h:755
	RigFuncMn = (uint64(1) << 13)
	// RigFuncRf as defined in hamlib/rig.h:756
	RigFuncRf = (uint64(1) << 14)
	// RigFuncAro as defined in hamlib/rig.h:757
	RigFuncAro = (uint64(1) << 15)
	// RigFuncLock as defined in hamlib/rig.h:758
	RigFuncLock = (uint64(1) << 16)
	// RigFuncMute as defined in hamlib/rig.h:759
	RigFuncMute = (uint64(1) << 17)
	// RigFuncVsc as defined in hamlib/rig.h:760
	RigFuncVsc = (uint64(1) << 18)
	// RigFuncRev as defined in hamlib/rig.h:761
	RigFuncRev = (uint64(1) << 19)
	// RigFuncSql as defined in hamlib/rig.h:762
	RigFuncSql = (uint64(1) << 20)
	// RigFuncAbm as defined in hamlib/rig.h:763
	RigFuncAbm = (uint64(1) << 21)
	// RigFuncBc as defined in hamlib/rig.h:764
	RigFuncBc = (uint64(1) << 22)
	// RigFuncMbc as defined in hamlib/rig.h:765
	RigFuncMbc = (uint64(1) << 23)
	// RigFuncRit as defined in hamlib/rig.h:766
	RigFuncRit = (uint64(1) << 24)
	// RigFuncAfc as defined in hamlib/rig.h:767
	RigFuncAfc = (uint64(1) << 25)
	// RigFuncSatmode as defined in hamlib/rig.h:768
	RigFuncSatmode = (uint64(1) << 26)
	// RigFuncScope as defined in hamlib/rig.h:769
	RigFuncScope = (uint64(1) << 27)
	// RigFuncResume as defined in hamlib/rig.h:770
	RigFuncResume = (uint64(1) << 28)
	// RigFuncTburst as defined in hamlib/rig.h:771
	RigFuncTburst = (uint64(1) << 29)
	// RigFuncTuner as defined in hamlib/rig.h:772
	RigFuncTuner = (uint64(1) << 30)
	// RigFuncXit as defined in hamlib/rig.h:773
	RigFuncXit = (uint64(1) << 31)
	// RigModeSsb as defined in hamlib/rig.h:821
	RigModeSsb = 0
	// RigModeEcss as defined in hamlib/rig.h:824
	RigModeEcss = 0
	// RigDblstEnd as defined in hamlib/rig.h:827
	RigDblstEnd = 0
	// RigItuRegion1 as defined in hamlib/rig.h:849
	RigItuRegion1 = 1
	// RigItuRegion2 as defined in hamlib/rig.h:850
	RigItuRegion2 = 2
	// RigItuRegion3 as defined in hamlib/rig.h:851
	RigItuRegion3 = 3
	// RigTsAny as defined in hamlib/rig.h:877
	RigTsAny = 0
	// RigFltAny as defined in hamlib/rig.h:912
	RigFltAny = 0
	// RigChflagNone as defined in hamlib/rig.h:918
	RigChflagNone = 0
	// RigChflagSkip as defined in hamlib/rig.h:920
	RigChflagSkip = (1 << 0)
	// RigChflagData as defined in hamlib/rig.h:922
	RigChflagData = (1 << 1)
	// RigMemCapsAll as defined in hamlib/rig.h:1062
	RigMemCapsAll = -1
	// RigModelNone as defined in hamlib/riglist.h:44
	RigModelNone = 0
	// RigDummy as defined in hamlib/riglist.h:54
	RigDummy = 0
	// RigBackendDummy as defined in hamlib/riglist.h:55
	RigBackendDummy = "dummy"
	// RigModelDummy as defined in hamlib/riglist.h:56
	RigModelDummy = 1
	// RigModelNetrigctl as defined in hamlib/riglist.h:57
	RigModelNetrigctl = 2
	// RigModelArmstrong as defined in hamlib/riglist.h:58
	RigModelArmstrong = 3
	// RigYaesu as defined in hamlib/riglist.h:63
	RigYaesu = 1
	// RigBackendYaesu as defined in hamlib/riglist.h:64
	RigBackendYaesu = "yaesu"
	// RigModelFt847 as defined in hamlib/riglist.h:65
	RigModelFt847 = 101
	// RigModelFt1000 as defined in hamlib/riglist.h:66
	RigModelFt1000 = 102
	// RigModelFt1000d as defined in hamlib/riglist.h:67
	RigModelFt1000d = 103
	// RigModelFt1000mpmkv as defined in hamlib/riglist.h:68
	RigModelFt1000mpmkv = 104
	// RigModelFt747 as defined in hamlib/riglist.h:69
	RigModelFt747 = 105
	// RigModelFt757 as defined in hamlib/riglist.h:70
	RigModelFt757 = 106
	// RigModelFt757gxii as defined in hamlib/riglist.h:71
	RigModelFt757gxii = 107
	// RigModelFt575 as defined in hamlib/riglist.h:72
	RigModelFt575 = 108
	// RigModelFt767 as defined in hamlib/riglist.h:73
	RigModelFt767 = 109
	// RigModelFt736r as defined in hamlib/riglist.h:74
	RigModelFt736r = 110
	// RigModelFt840 as defined in hamlib/riglist.h:75
	RigModelFt840 = 111
	// RigModelFt820 as defined in hamlib/riglist.h:76
	RigModelFt820 = 112
	// RigModelFt900 as defined in hamlib/riglist.h:77
	RigModelFt900 = 113
	// RigModelFt920 as defined in hamlib/riglist.h:78
	RigModelFt920 = 114
	// RigModelFt890 as defined in hamlib/riglist.h:79
	RigModelFt890 = 115
	// RigModelFt990 as defined in hamlib/riglist.h:80
	RigModelFt990 = 116
	// RigModelFrg100 as defined in hamlib/riglist.h:81
	RigModelFrg100 = 117
	// RigModelFrg9600 as defined in hamlib/riglist.h:82
	RigModelFrg9600 = 118
	// RigModelFrg8800 as defined in hamlib/riglist.h:83
	RigModelFrg8800 = 119
	// RigModelFt817 as defined in hamlib/riglist.h:84
	RigModelFt817 = 120
	// RigModelFt100 as defined in hamlib/riglist.h:85
	RigModelFt100 = 121
	// RigModelFt857 as defined in hamlib/riglist.h:86
	RigModelFt857 = 122
	// RigModelFt897 as defined in hamlib/riglist.h:87
	RigModelFt897 = 123
	// RigModelFt1000mp as defined in hamlib/riglist.h:88
	RigModelFt1000mp = 124
	// RigModelFt1000mpmkvfld as defined in hamlib/riglist.h:89
	RigModelFt1000mpmkvfld = 125
	// RigModelVr5000 as defined in hamlib/riglist.h:90
	RigModelVr5000 = 126
	// RigModelFt450 as defined in hamlib/riglist.h:91
	RigModelFt450 = 127
	// RigModelFt950 as defined in hamlib/riglist.h:92
	RigModelFt950 = 128
	// RigModelFt2000 as defined in hamlib/riglist.h:93
	RigModelFt2000 = 129
	// RigModelFt9000 as defined in hamlib/riglist.h:94
	RigModelFt9000 = 130
	// RigModelFt980 as defined in hamlib/riglist.h:95
	RigModelFt980 = 131
	// RigModelFtdx5000 as defined in hamlib/riglist.h:96
	RigModelFtdx5000 = 132
	// RigModelVx1700 as defined in hamlib/riglist.h:97
	RigModelVx1700 = 133
	// RigKenwood as defined in hamlib/riglist.h:102
	RigKenwood = 2
	// RigBackendKenwood as defined in hamlib/riglist.h:103
	RigBackendKenwood = "kenwood"
	// RigModelTs50 as defined in hamlib/riglist.h:104
	RigModelTs50 = 201
	// RigModelTs440 as defined in hamlib/riglist.h:105
	RigModelTs440 = 202
	// RigModelTs450s as defined in hamlib/riglist.h:106
	RigModelTs450s = 203
	// RigModelTs570d as defined in hamlib/riglist.h:107
	RigModelTs570d = 204
	// RigModelTs690s as defined in hamlib/riglist.h:108
	RigModelTs690s = 205
	// RigModelTs711 as defined in hamlib/riglist.h:109
	RigModelTs711 = 206
	// RigModelTs790 as defined in hamlib/riglist.h:110
	RigModelTs790 = 207
	// RigModelTs811 as defined in hamlib/riglist.h:111
	RigModelTs811 = 208
	// RigModelTs850 as defined in hamlib/riglist.h:112
	RigModelTs850 = 209
	// RigModelTs870s as defined in hamlib/riglist.h:113
	RigModelTs870s = 210
	// RigModelTs940 as defined in hamlib/riglist.h:114
	RigModelTs940 = 211
	// RigModelTs950 as defined in hamlib/riglist.h:115
	RigModelTs950 = 212
	// RigModelTs950sdx as defined in hamlib/riglist.h:116
	RigModelTs950sdx = 213
	// RigModelTs2000 as defined in hamlib/riglist.h:117
	RigModelTs2000 = 214
	// RigModelR5000 as defined in hamlib/riglist.h:118
	RigModelR5000 = 215
	// RigModelTs570s as defined in hamlib/riglist.h:119
	RigModelTs570s = 216
	// RigModelThd7a as defined in hamlib/riglist.h:120
	RigModelThd7a = 217
	// RigModelThd7ag as defined in hamlib/riglist.h:121
	RigModelThd7ag = 218
	// RigModelThf6a as defined in hamlib/riglist.h:122
	RigModelThf6a = 219
	// RigModelThf7e as defined in hamlib/riglist.h:123
	RigModelThf7e = 220
	// RigModelK2 as defined in hamlib/riglist.h:124
	RigModelK2 = 221
	// RigModelTs930 as defined in hamlib/riglist.h:125
	RigModelTs930 = 222
	// RigModelThg71 as defined in hamlib/riglist.h:126
	RigModelThg71 = 223
	// RigModelTs680s as defined in hamlib/riglist.h:127
	RigModelTs680s = 224
	// RigModelTs140s as defined in hamlib/riglist.h:128
	RigModelTs140s = 225
	// RigModelTmd700 as defined in hamlib/riglist.h:129
	RigModelTmd700 = 226
	// RigModelTmv7 as defined in hamlib/riglist.h:130
	RigModelTmv7 = 227
	// RigModelTs480 as defined in hamlib/riglist.h:131
	RigModelTs480 = 228
	// RigModelK3 as defined in hamlib/riglist.h:132
	RigModelK3 = 229
	// RigModelTrc80 as defined in hamlib/riglist.h:133
	RigModelTrc80 = 230
	// RigModelTs590s as defined in hamlib/riglist.h:134
	RigModelTs590s = 231
	// RigModelTransfox as defined in hamlib/riglist.h:135
	RigModelTransfox = 232
	// RigModelThd72a as defined in hamlib/riglist.h:136
	RigModelThd72a = 233
	// RigModelTmd710 as defined in hamlib/riglist.h:137
	RigModelTmd710 = 234
	// RigModelTmv71 as defined in hamlib/riglist.h:138
	RigModelTmv71 = 235
	// RigIcom as defined in hamlib/riglist.h:143
	RigIcom = 3
	// RigBackendIcom as defined in hamlib/riglist.h:144
	RigBackendIcom = "icom"
	// RigModelIc1271 as defined in hamlib/riglist.h:145
	RigModelIc1271 = 301
	// RigModelIc1275 as defined in hamlib/riglist.h:146
	RigModelIc1275 = 302
	// RigModelIc271 as defined in hamlib/riglist.h:147
	RigModelIc271 = 303
	// RigModelIc275 as defined in hamlib/riglist.h:148
	RigModelIc275 = 304
	// RigModelIc375 as defined in hamlib/riglist.h:149
	RigModelIc375 = 305
	// RigModelIc471 as defined in hamlib/riglist.h:150
	RigModelIc471 = 306
	// RigModelIc475 as defined in hamlib/riglist.h:151
	RigModelIc475 = 307
	// RigModelIc575 as defined in hamlib/riglist.h:152
	RigModelIc575 = 308
	// RigModelIc706 as defined in hamlib/riglist.h:153
	RigModelIc706 = 309
	// RigModelIc706mkii as defined in hamlib/riglist.h:154
	RigModelIc706mkii = 310
	// RigModelIc706mkiig as defined in hamlib/riglist.h:155
	RigModelIc706mkiig = 311
	// RigModelIc707 as defined in hamlib/riglist.h:156
	RigModelIc707 = 312
	// RigModelIc718 as defined in hamlib/riglist.h:157
	RigModelIc718 = 313
	// RigModelIc725 as defined in hamlib/riglist.h:158
	RigModelIc725 = 314
	// RigModelIc726 as defined in hamlib/riglist.h:159
	RigModelIc726 = 315
	// RigModelIc728 as defined in hamlib/riglist.h:160
	RigModelIc728 = 316
	// RigModelIc729 as defined in hamlib/riglist.h:161
	RigModelIc729 = 317
	// RigModelIc731 as defined in hamlib/riglist.h:162
	RigModelIc731 = 318
	// RigModelIc735 as defined in hamlib/riglist.h:163
	RigModelIc735 = 319
	// RigModelIc736 as defined in hamlib/riglist.h:164
	RigModelIc736 = 320
	// RigModelIc737 as defined in hamlib/riglist.h:165
	RigModelIc737 = 321
	// RigModelIc738 as defined in hamlib/riglist.h:166
	RigModelIc738 = 322
	// RigModelIc746 as defined in hamlib/riglist.h:167
	RigModelIc746 = 323
	// RigModelIc751 as defined in hamlib/riglist.h:168
	RigModelIc751 = 324
	// RigModelIc751a as defined in hamlib/riglist.h:169
	RigModelIc751a = 325
	// RigModelIc756 as defined in hamlib/riglist.h:170
	RigModelIc756 = 326
	// RigModelIc756pro as defined in hamlib/riglist.h:171
	RigModelIc756pro = 327
	// RigModelIc761 as defined in hamlib/riglist.h:172
	RigModelIc761 = 328
	// RigModelIc765 as defined in hamlib/riglist.h:173
	RigModelIc765 = 329
	// RigModelIc775 as defined in hamlib/riglist.h:174
	RigModelIc775 = 330
	// RigModelIc781 as defined in hamlib/riglist.h:175
	RigModelIc781 = 331
	// RigModelIc820 as defined in hamlib/riglist.h:176
	RigModelIc820 = 332
	// RigModelIc821 as defined in hamlib/riglist.h:177
	RigModelIc821 = 333
	// RigModelIc821h as defined in hamlib/riglist.h:178
	RigModelIc821h = 334
	// RigModelIc970 as defined in hamlib/riglist.h:179
	RigModelIc970 = 335
	// RigModelIcr10 as defined in hamlib/riglist.h:180
	RigModelIcr10 = 336
	// RigModelIcr71 as defined in hamlib/riglist.h:181
	RigModelIcr71 = 337
	// RigModelIcr72 as defined in hamlib/riglist.h:182
	RigModelIcr72 = 338
	// RigModelIcr75 as defined in hamlib/riglist.h:183
	RigModelIcr75 = 339
	// RigModelIcr7000 as defined in hamlib/riglist.h:184
	RigModelIcr7000 = 340
	// RigModelIcr7100 as defined in hamlib/riglist.h:185
	RigModelIcr7100 = 341
	// RigModelIcr8500 as defined in hamlib/riglist.h:186
	RigModelIcr8500 = 342
	// RigModelIcr9000 as defined in hamlib/riglist.h:187
	RigModelIcr9000 = 343
	// RigModelIc910 as defined in hamlib/riglist.h:188
	RigModelIc910 = 344
	// RigModelIc78 as defined in hamlib/riglist.h:189
	RigModelIc78 = 345
	// RigModelIc746pro as defined in hamlib/riglist.h:190
	RigModelIc746pro = 346
	// RigModelIc756proii as defined in hamlib/riglist.h:191
	RigModelIc756proii = 347
	// RigModelIcid1 as defined in hamlib/riglist.h:192
	RigModelIcid1 = 354
	// RigModelIc703 as defined in hamlib/riglist.h:193
	RigModelIc703 = 355
	// RigModelIc7800 as defined in hamlib/riglist.h:194
	RigModelIc7800 = 356
	// RigModelIc756proiii as defined in hamlib/riglist.h:195
	RigModelIc756proiii = 357
	// RigModelIcr20 as defined in hamlib/riglist.h:196
	RigModelIcr20 = 358
	// RigModelIc7000 as defined in hamlib/riglist.h:197
	RigModelIc7000 = 360
	// RigModelIc7200 as defined in hamlib/riglist.h:198
	RigModelIc7200 = 361
	// RigModelIc7700 as defined in hamlib/riglist.h:199
	RigModelIc7700 = 362
	// RigModelIc7600 as defined in hamlib/riglist.h:200
	RigModelIc7600 = 363
	// RigModelIc92d as defined in hamlib/riglist.h:201
	RigModelIc92d = 365
	// RigModelIcr9500 as defined in hamlib/riglist.h:202
	RigModelIcr9500 = 366
	// RigModelIc7410 as defined in hamlib/riglist.h:203
	RigModelIc7410 = 367
	// RigModelIc9100 as defined in hamlib/riglist.h:204
	RigModelIc9100 = 368
	// RigModelIcrx7 as defined in hamlib/riglist.h:205
	RigModelIcrx7 = 369
	// RigModelMiniscout as defined in hamlib/riglist.h:211
	RigModelMiniscout = 348
	// RigModelXplorer as defined in hamlib/riglist.h:212
	RigModelXplorer = 349
	// RigModelOs535 as defined in hamlib/riglist.h:213
	RigModelOs535 = 352
	// RigModelOs456 as defined in hamlib/riglist.h:214
	RigModelOs456 = 353
	// RigModelOmnivi as defined in hamlib/riglist.h:219
	RigModelOmnivi = 350
	// RigModelOmnivip as defined in hamlib/riglist.h:220
	RigModelOmnivip = 351
	// RigModelParagon2 as defined in hamlib/riglist.h:221
	RigModelParagon2 = 359
	// RigModelDeltaii as defined in hamlib/riglist.h:222
	RigModelDeltaii = 364
	// RigPcr as defined in hamlib/riglist.h:227
	RigPcr = 4
	// RigBackendPcr as defined in hamlib/riglist.h:228
	RigBackendPcr = "pcr"
	// RigModelPcr1000 as defined in hamlib/riglist.h:229
	RigModelPcr1000 = 401
	// RigModelPcr100 as defined in hamlib/riglist.h:230
	RigModelPcr100 = 402
	// RigModelPcr1500 as defined in hamlib/riglist.h:231
	RigModelPcr1500 = 403
	// RigModelPcr2500 as defined in hamlib/riglist.h:232
	RigModelPcr2500 = 404
	// RigAor as defined in hamlib/riglist.h:237
	RigAor = 5
	// RigBackendAor as defined in hamlib/riglist.h:238
	RigBackendAor = "aor"
	// RigModelAr8200 as defined in hamlib/riglist.h:239
	RigModelAr8200 = 501
	// RigModelAr8000 as defined in hamlib/riglist.h:240
	RigModelAr8000 = 502
	// RigModelAr7030 as defined in hamlib/riglist.h:241
	RigModelAr7030 = 503
	// RigModelAr5000 as defined in hamlib/riglist.h:242
	RigModelAr5000 = 504
	// RigModelAr3030 as defined in hamlib/riglist.h:243
	RigModelAr3030 = 505
	// RigModelAr3000a as defined in hamlib/riglist.h:244
	RigModelAr3000a = 506
	// RigModelAr3000 as defined in hamlib/riglist.h:245
	RigModelAr3000 = 507
	// RigModelAr2700 as defined in hamlib/riglist.h:246
	RigModelAr2700 = 508
	// RigModelAr2500 as defined in hamlib/riglist.h:247
	RigModelAr2500 = 509
	// RigModelAr16 as defined in hamlib/riglist.h:248
	RigModelAr16 = 510
	// RigModelSdu5500 as defined in hamlib/riglist.h:249
	RigModelSdu5500 = 511
	// RigModelSdu5000 as defined in hamlib/riglist.h:250
	RigModelSdu5000 = 512
	// RigModelAr8600 as defined in hamlib/riglist.h:251
	RigModelAr8600 = 513
	// RigModelAr5000a as defined in hamlib/riglist.h:252
	RigModelAr5000a = 514
	// RigModelAr7030p as defined in hamlib/riglist.h:253
	RigModelAr7030p = 515
	// RigModelSr2200 as defined in hamlib/riglist.h:254
	RigModelSr2200 = 516
	// RigJrc as defined in hamlib/riglist.h:259
	RigJrc = 6
	// RigBackendJrc as defined in hamlib/riglist.h:260
	RigBackendJrc = "jrc"
	// RigModelJst145 as defined in hamlib/riglist.h:261
	RigModelJst145 = 601
	// RigModelJst245 as defined in hamlib/riglist.h:262
	RigModelJst245 = 602
	// RigModelCmh530 as defined in hamlib/riglist.h:263
	RigModelCmh530 = 603
	// RigModelNrd345 as defined in hamlib/riglist.h:264
	RigModelNrd345 = 604
	// RigModelNrd525 as defined in hamlib/riglist.h:265
	RigModelNrd525 = 605
	// RigModelNrd535 as defined in hamlib/riglist.h:266
	RigModelNrd535 = 606
	// RigModelNrd545 as defined in hamlib/riglist.h:267
	RigModelNrd545 = 607
	// RigRadioshack as defined in hamlib/riglist.h:273
	RigRadioshack = 7
	// RigBackendRadioshack as defined in hamlib/riglist.h:274
	RigBackendRadioshack = "radioshack"
	// RigModelRs64 as defined in hamlib/riglist.h:275
	RigModelRs64 = 701
	// RigModelRs2005 as defined in hamlib/riglist.h:276
	RigModelRs2005 = 702
	// RigModelRs2006 as defined in hamlib/riglist.h:277
	RigModelRs2006 = 703
	// RigModelRs2035 as defined in hamlib/riglist.h:278
	RigModelRs2035 = 704
	// RigModelRs2042 as defined in hamlib/riglist.h:279
	RigModelRs2042 = 705
	// RigModelRs2041 as defined in hamlib/riglist.h:280
	RigModelRs2041 = 706
	// RigUniden as defined in hamlib/riglist.h:285
	RigUniden = 8
	// RigBackendUniden as defined in hamlib/riglist.h:286
	RigBackendUniden = "uniden"
	// RigModelBc780 as defined in hamlib/riglist.h:287
	RigModelBc780 = 801
	// RigModelBc245 as defined in hamlib/riglist.h:288
	RigModelBc245 = 802
	// RigModelBc895 as defined in hamlib/riglist.h:289
	RigModelBc895 = 803
	// RigModelPro2052 as defined in hamlib/riglist.h:290
	RigModelPro2052 = 804
	// RigModelBc235 as defined in hamlib/riglist.h:291
	RigModelBc235 = 805
	// RigModelBc250 as defined in hamlib/riglist.h:292
	RigModelBc250 = 806
	// RigModelBc785 as defined in hamlib/riglist.h:293
	RigModelBc785 = 807
	// RigModelBc786 as defined in hamlib/riglist.h:294
	RigModelBc786 = 808
	// RigModelBct8 as defined in hamlib/riglist.h:295
	RigModelBct8 = 809
	// RigModelBcd396t as defined in hamlib/riglist.h:296
	RigModelBcd396t = 810
	// RigModelBcd996t as defined in hamlib/riglist.h:297
	RigModelBcd996t = 811
	// RigModelBc898 as defined in hamlib/riglist.h:298
	RigModelBc898 = 812
	// RigDrake as defined in hamlib/riglist.h:303
	RigDrake = 9
	// RigBackendDrake as defined in hamlib/riglist.h:304
	RigBackendDrake = "drake"
	// RigModelDkr8 as defined in hamlib/riglist.h:305
	RigModelDkr8 = 901
	// RigModelDkr8a as defined in hamlib/riglist.h:306
	RigModelDkr8a = 902
	// RigModelDkr8b as defined in hamlib/riglist.h:307
	RigModelDkr8b = 903
	// RigLowe as defined in hamlib/riglist.h:312
	RigLowe = 10
	// RigBackendLowe as defined in hamlib/riglist.h:313
	RigBackendLowe = "lowe"
	// RigModelHf150 as defined in hamlib/riglist.h:314
	RigModelHf150 = 1001
	// RigModelHf225 as defined in hamlib/riglist.h:315
	RigModelHf225 = 1002
	// RigModelHf250 as defined in hamlib/riglist.h:316
	RigModelHf250 = 1003
	// RigModelHf235 as defined in hamlib/riglist.h:317
	RigModelHf235 = 1004
	// RigRacal as defined in hamlib/riglist.h:322
	RigRacal = 11
	// RigBackendRacal as defined in hamlib/riglist.h:323
	RigBackendRacal = "racal"
	// RigModelRa3790 as defined in hamlib/riglist.h:324
	RigModelRa3790 = 1101
	// RigModelRa3720 as defined in hamlib/riglist.h:325
	RigModelRa3720 = 1102
	// RigModelRa6790 as defined in hamlib/riglist.h:326
	RigModelRa6790 = 1103
	// RigModelRa3710 as defined in hamlib/riglist.h:327
	RigModelRa3710 = 1104
	// RigModelRa3702 as defined in hamlib/riglist.h:328
	RigModelRa3702 = 1105
	// RigWj as defined in hamlib/riglist.h:333
	RigWj = 12
	// RigBackendWj as defined in hamlib/riglist.h:334
	RigBackendWj = "wj"
	// RigModelHf1000 as defined in hamlib/riglist.h:335
	RigModelHf1000 = 1201
	// RigModelHf1000a as defined in hamlib/riglist.h:336
	RigModelHf1000a = 1202
	// RigModelWj8711 as defined in hamlib/riglist.h:337
	RigModelWj8711 = 1203
	// RigModelWj8888 as defined in hamlib/riglist.h:338
	RigModelWj8888 = 1204
	// RigEk as defined in hamlib/riglist.h:343
	RigEk = 13
	// RigBackendEk as defined in hamlib/riglist.h:344
	RigBackendEk = "ek"
	// RigModelEsm500 as defined in hamlib/riglist.h:345
	RigModelEsm500 = 1301
	// RigModelEk890 as defined in hamlib/riglist.h:346
	RigModelEk890 = 1302
	// RigModelEk891 as defined in hamlib/riglist.h:347
	RigModelEk891 = 1303
	// RigModelEk895 as defined in hamlib/riglist.h:348
	RigModelEk895 = 1304
	// RigModelEk070 as defined in hamlib/riglist.h:349
	RigModelEk070 = 1305
	// RigSkanti as defined in hamlib/riglist.h:354
	RigSkanti = 14
	// RigBackendSkanti as defined in hamlib/riglist.h:355
	RigBackendSkanti = "skanti"
	// RigModelTrp7000 as defined in hamlib/riglist.h:356
	RigModelTrp7000 = 1401
	// RigModelTrp8000 as defined in hamlib/riglist.h:357
	RigModelTrp8000 = 1402
	// RigModelTrp9000 as defined in hamlib/riglist.h:358
	RigModelTrp9000 = 1403
	// RigModelTrp8255 as defined in hamlib/riglist.h:359
	RigModelTrp8255 = 1404
	// RigWinradio as defined in hamlib/riglist.h:364
	RigWinradio = 15
	// RigBackendWinradio as defined in hamlib/riglist.h:365
	RigBackendWinradio = "winradio"
	// RigModelWr1000 as defined in hamlib/riglist.h:366
	RigModelWr1000 = 1501
	// RigModelWr1500 as defined in hamlib/riglist.h:367
	RigModelWr1500 = 1502
	// RigModelWr1550 as defined in hamlib/riglist.h:368
	RigModelWr1550 = 1503
	// RigModelWr3100 as defined in hamlib/riglist.h:369
	RigModelWr3100 = 1504
	// RigModelWr3150 as defined in hamlib/riglist.h:370
	RigModelWr3150 = 1505
	// RigModelWr3500 as defined in hamlib/riglist.h:371
	RigModelWr3500 = 1506
	// RigModelWr3700 as defined in hamlib/riglist.h:372
	RigModelWr3700 = 1507
	// RigModelG303 as defined in hamlib/riglist.h:373
	RigModelG303 = 1508
	// RigModelG313 as defined in hamlib/riglist.h:374
	RigModelG313 = 1509
	// RigModelG305 as defined in hamlib/riglist.h:375
	RigModelG305 = 1510
	// RigModelG315 as defined in hamlib/riglist.h:376
	RigModelG315 = 1511
	// RigTentec as defined in hamlib/riglist.h:381
	RigTentec = 16
	// RigBackendTentec as defined in hamlib/riglist.h:382
	RigBackendTentec = "tentec"
	// RigModelTt550 as defined in hamlib/riglist.h:383
	RigModelTt550 = 1601
	// RigModelTt538 as defined in hamlib/riglist.h:384
	RigModelTt538 = 1602
	// RigModelRx320 as defined in hamlib/riglist.h:385
	RigModelRx320 = 1603
	// RigModelRx340 as defined in hamlib/riglist.h:386
	RigModelRx340 = 1604
	// RigModelRx350 as defined in hamlib/riglist.h:387
	RigModelRx350 = 1605
	// RigModelTt526 as defined in hamlib/riglist.h:388
	RigModelTt526 = 1606
	// RigModelTt516 as defined in hamlib/riglist.h:389
	RigModelTt516 = 1607
	// RigModelTt565 as defined in hamlib/riglist.h:390
	RigModelTt565 = 1608
	// RigModelTt585 as defined in hamlib/riglist.h:391
	RigModelTt585 = 1609
	// RigModelTt588 as defined in hamlib/riglist.h:392
	RigModelTt588 = 1611
	// RigModelRx331 as defined in hamlib/riglist.h:393
	RigModelRx331 = 1612
	// RigModelTt599 as defined in hamlib/riglist.h:394
	RigModelTt599 = 1613
	// RigAlinco as defined in hamlib/riglist.h:399
	RigAlinco = 17
	// RigBackendAlinco as defined in hamlib/riglist.h:400
	RigBackendAlinco = "alinco"
	// RigModelDx77 as defined in hamlib/riglist.h:401
	RigModelDx77 = 1701
	// RigKachina as defined in hamlib/riglist.h:406
	RigKachina = 18
	// RigBackendKachina as defined in hamlib/riglist.h:407
	RigBackendKachina = "kachina"
	// RigModel505dsp as defined in hamlib/riglist.h:408
	RigModel505dsp = 1801
	// RigRpc as defined in hamlib/riglist.h:418
	RigRpc = 19
	// RigBackendRpc as defined in hamlib/riglist.h:419
	RigBackendRpc = "rpcrig"
	// RigModelRpc as defined in hamlib/riglist.h:420
	RigModelRpc = 1901
	// RigGnuradio as defined in hamlib/riglist.h:425
	RigGnuradio = 20
	// RigBackendGnuradio as defined in hamlib/riglist.h:426
	RigBackendGnuradio = "gnuradio"
	// RigModelGnuradio as defined in hamlib/riglist.h:427
	RigModelGnuradio = 2001
	// RigModelMc4020 as defined in hamlib/riglist.h:428
	RigModelMc4020 = 2002
	// RigModelGraudio as defined in hamlib/riglist.h:429
	RigModelGraudio = 2003
	// RigModelGraudioiq as defined in hamlib/riglist.h:430
	RigModelGraudioiq = 2004
	// RigModelUsrpG as defined in hamlib/riglist.h:431
	RigModelUsrpG = 2005
	// RigMicrotune as defined in hamlib/riglist.h:436
	RigMicrotune = 21
	// RigBackendMicrotune as defined in hamlib/riglist.h:437
	RigBackendMicrotune = "microtune"
	// RigModelMicrotune4937 as defined in hamlib/riglist.h:438
	RigModelMicrotune4937 = 2101
	// RigModelMicrotune4702 as defined in hamlib/riglist.h:439
	RigModelMicrotune4702 = 2102
	// RigModelMicrotune4707 as defined in hamlib/riglist.h:440
	RigModelMicrotune4707 = 2103
	// RigTapr as defined in hamlib/riglist.h:445
	RigTapr = 22
	// RigBackendTapr as defined in hamlib/riglist.h:446
	RigBackendTapr = "tapr"
	// RigModelDsp10 as defined in hamlib/riglist.h:447
	RigModelDsp10 = 2201
	// RigFlexradio as defined in hamlib/riglist.h:452
	RigFlexradio = 23
	// RigBackendFlexradio as defined in hamlib/riglist.h:453
	RigBackendFlexradio = "flexradio"
	// RigModelSdr1000 as defined in hamlib/riglist.h:454
	RigModelSdr1000 = 2301
	// RigModelSdr1000rfe as defined in hamlib/riglist.h:455
	RigModelSdr1000rfe = 2302
	// RigModelDttsp as defined in hamlib/riglist.h:456
	RigModelDttsp = 2303
	// RigModelDttspUdp as defined in hamlib/riglist.h:457
	RigModelDttspUdp = 2304
	// RigRft as defined in hamlib/riglist.h:463
	RigRft = 24
	// RigBackendRft as defined in hamlib/riglist.h:464
	RigBackendRft = "rft"
	// RigModelEkd500 as defined in hamlib/riglist.h:465
	RigModelEkd500 = 2401
	// RigKit as defined in hamlib/riglist.h:470
	RigKit = 25
	// RigBackendKit as defined in hamlib/riglist.h:471
	RigBackendKit = "kit"
	// RigModelElektor304 as defined in hamlib/riglist.h:472
	RigModelElektor304 = 2501
	// RigModelDrt1 as defined in hamlib/riglist.h:473
	RigModelDrt1 = 2502
	// RigModelDwt as defined in hamlib/riglist.h:474
	RigModelDwt = 2503
	// RigModelUsrp0 as defined in hamlib/riglist.h:475
	RigModelUsrp0 = 2504
	// RigModelUsrp as defined in hamlib/riglist.h:476
	RigModelUsrp = 2505
	// RigModelDds60 as defined in hamlib/riglist.h:477
	RigModelDds60 = 2506
	// RigModelElektor507 as defined in hamlib/riglist.h:478
	RigModelElektor507 = 2507
	// RigModelMinivna as defined in hamlib/riglist.h:479
	RigModelMinivna = 2508
	// RigModelSi570avrusb as defined in hamlib/riglist.h:480
	RigModelSi570avrusb = 2509
	// RigModelPmsdr as defined in hamlib/riglist.h:481
	RigModelPmsdr = 2510
	// RigModelSi570picusb as defined in hamlib/riglist.h:482
	RigModelSi570picusb = 2511
	// RigModelFifisdr as defined in hamlib/riglist.h:483
	RigModelFifisdr = 2512
	// RigModelFuncubedongle as defined in hamlib/riglist.h:484
	RigModelFuncubedongle = 2513
	// RigModelHiqsdr as defined in hamlib/riglist.h:485
	RigModelHiqsdr = 2514
	// RigTuner as defined in hamlib/riglist.h:490
	RigTuner = 26
	// RigBackendTuner as defined in hamlib/riglist.h:491
	RigBackendTuner = "tuner"
	// RigModelV4l as defined in hamlib/riglist.h:492
	RigModelV4l = 2601
	// RigModelV4l2 as defined in hamlib/riglist.h:493
	RigModelV4l2 = 2602
	// RigRs as defined in hamlib/riglist.h:498
	RigRs = 27
	// RigBackendRs as defined in hamlib/riglist.h:499
	RigBackendRs = "rs"
	// RigModelEsmc as defined in hamlib/riglist.h:500
	RigModelEsmc = 2701
	// RigModelEb200 as defined in hamlib/riglist.h:501
	RigModelEb200 = 2702
	// RigPrm80 as defined in hamlib/riglist.h:506
	RigPrm80 = 28
	// RigBackendPrm80 as defined in hamlib/riglist.h:507
	RigBackendPrm80 = "prm80"
	// RigModelPrm8060 as defined in hamlib/riglist.h:508
	RigModelPrm8060 = 2801
	// RigModelPrm8070 as defined in hamlib/riglist.h:509
	RigModelPrm8070 = 2802
	// RigAdat as defined in hamlib/riglist.h:516
	RigAdat = 29
	// RigBackendAdat as defined in hamlib/riglist.h:517
	RigBackendAdat = "adat"
	// RigModelAdt200a as defined in hamlib/riglist.h:518
	RigModelAdt200a = 2901
)

// RigErrcodeE as declared in hamlib/rig.h:86
type RigErrcodeE int32

// RigErrcodeE enumeration from hamlib/rig.h:86
const (
	RigOk        = iota
	RigEinval    = 1
	RigEconf     = 2
	RigEnomem    = 3
	RigEnimpl    = 4
	RigEtimeout  = 5
	RigEio       = 6
	RigEinternal = 7
	RigEproto    = 8
	RigErjcted   = 9
	RigEtrunc    = 10
	RigEnavail   = 11
	RigEntarget  = 12
	RigBuserror  = 13
	RigBusbusy   = 14
	RigEarg      = 15
	RigEvfo      = 16
	RigEdom      = 17
)

// RigDebugLevelE as declared in hamlib/rig.h:117
type RigDebugLevelE int32

// RigDebugLevelE enumeration from hamlib/rig.h:117
const (
	RigDebugNone    = iota
	RigDebugBug     = 1
	RigDebugErr     = 2
	RigDebugWarn    = 3
	RigDebugVerbose = 4
	RigDebugTrace   = 5
)

// RigPort as declared in hamlib/rig.h:180
type RigPort int32

// RigPort enumeration from hamlib/rig.h:180
const (
	RigPortNone       RigPort = iota
	RigPortSerial     RigPort = 1
	RigPortNetwork    RigPort = 2
	RigPortDevice     RigPort = 3
	RigPortPacket     RigPort = 4
	RigPortDtmf       RigPort = 5
	RigPortUltra      RigPort = 6
	RigPortRpc        RigPort = 7
	RigPortParallel   RigPort = 8
	RigPortUsb        RigPort = 9
	RigPortUdpNetwork RigPort = 10
	RigPortCm108      RigPort = 11
	RigPortGpio       RigPort = 12
	RigPortGpion      RigPort = 13
)

// RigStatusE as declared in hamlib/rig.h:246
type RigStatusE int32

// RigStatusE enumeration from hamlib/rig.h:246
const (
	RigStatusAlpha    = iota
	RigStatusUntested = 1
	RigStatusBeta     = 2
	RigStatusStable   = 3
	RigStatusBuggy    = 4
)

// RigConfE as declared in hamlib/rig.h:526
type RigConfE int32

// RigConfE enumeration from hamlib/rig.h:526
const (
	RigConfString      = iota
	RigConfCombo       = 1
	RigConfNumeric     = 2
	RigConfCheckbutton = 3
	RigConfButton      = 4
)

// RigLevelE as declared in hamlib/rig.h:633
type RigLevelE int32

// RigLevelE enumeration from hamlib/rig.h:633
const (
	RigLevelNone      = iota
	RigLevelPreamp    = (1 << 0)
	RigLevelAtt       = (1 << 1)
	RigLevelVox       = (1 << 2)
	RigLevelAf        = (1 << 3)
	RigLevelRf        = (1 << 4)
	RigLevelSql       = (1 << 5)
	RigLevelIf        = (1 << 6)
	RigLevelApf       = (1 << 7)
	RigLevelNr        = (1 << 8)
	RigLevelPbtIn     = (1 << 9)
	RigLevelPbtOut    = (1 << 10)
	RigLevelCwpitch   = (1 << 11)
	RigLevelRfpower   = (1 << 12)
	RigLevelMicgain   = (1 << 13)
	RigLevelKeyspd    = (1 << 14)
	RigLevelNotchf    = (1 << 15)
	RigLevelComp      = (1 << 16)
	RigLevelAgc       = (1 << 17)
	RigLevelBkindl    = (1 << 18)
	RigLevelBalance   = (1 << 19)
	RigLevelMeter     = (1 << 20)
	RigLevelVoxgain   = (1 << 21)
	RigLevelVoxdelay  = RigLevelVox
	RigLevelAntivox   = (1 << 22)
	RigLevelSlopeLow  = (1 << 23)
	RigLevelSlopeHigh = (1 << 24)
	RigLevelBkinDlyms = (1 << 25)
	RigLevelRawstr    = (1 << 26)
	RigLevelSqlstat   = (1 << 27)
	RigLevelSwr       = (1 << 28)
	RigLevelAlc       = (1 << 29)
	RigLevelStrength  = (1 << 30)
)

// RigParmE as declared in hamlib/rig.h:689
type RigParmE int32

// RigParmE enumeration from hamlib/rig.h:689
const (
	RigParmNone      = iota
	RigParmAnn       = (1 << 0)
	RigParmApo       = (1 << 1)
	RigParmBacklight = (1 << 2)
	RigParmBeep      = (1 << 4)
	RigParmTime      = (1 << 5)
	RigParmBat       = (1 << 6)
	RigParmKeylight  = (1 << 7)
)

// RigType as declared in hamlib/rig.h:226
type RigType int32

// RigType enumeration from hamlib/rig.h:226
const (
	RigFlagReceiver    RigType = (1 << 1)
	RigFlagTransmitter RigType = (1 << 2)
	RigFlagScanner     RigType = (1 << 3)
	RigFlagMobile      RigType = (1 << 4)
	RigFlagHandheld    RigType = (1 << 5)
	RigFlagComputer    RigType = (1 << 6)
	RigFlagTrunking    RigType = (1 << 7)
	RigFlagAprs        RigType = (1 << 8)
	RigFlagTnc         RigType = (1 << 9)
	RigFlagDxcluster   RigType = (1 << 10)
	RigFlagTuner       RigType = (1 << 11)
)

// RptrShift as declared in hamlib/rig.h:266
type RptrShift int32

// RptrShift enumeration from hamlib/rig.h:266
const (
	RigRptShiftNone  RptrShift = iota
	RigRptShiftMinus RptrShift = 1
	RigRptShiftPlus  RptrShift = 2
)

// Split as declared in hamlib/rig.h:274
type Split int32

// Split enumeration from hamlib/rig.h:274
const (
	RigSplitOff Split = iota
	RigSplitOn  Split = 1
)

// Dcd as declared in hamlib/rig.h:388
type Dcd int32

// Dcd enumeration from hamlib/rig.h:388
const (
	RigDcdOff Dcd = iota
	RigDcdOn  Dcd = 1
)

// Ptt as declared in hamlib/rig.h:413
type Ptt int32

// Ptt enumeration from hamlib/rig.h:413
const (
	RigPttOff    Ptt = iota
	RigPttOn     Ptt = 1
	RigPttOnMic  Ptt = 2
	RigPttOnData Ptt = 3
)

// Powerstat as declared in hamlib/rig.h:438
type Powerstat int32

// Powerstat enumeration from hamlib/rig.h:438
const (
	RigPowerOff     Powerstat = iota
	RigPowerOn      Powerstat = (1 << 0)
	RigPowerStandby Powerstat = (1 << 1)
)

// Reset as declared in hamlib/rig.h:449
type Reset int32

// Reset enumeration from hamlib/rig.h:449
const (
	RigResetNone   Reset = iota
	RigResetSoft   Reset = (1 << 0)
	RigResetVfo    Reset = (1 << 1)
	RigResetMcall  Reset = (1 << 2)
	RigResetMaster Reset = (1 << 3)
)

// VfoOp as declared in hamlib/rig.h:482
type VfoOp int32

// VfoOp enumeration from hamlib/rig.h:482
const (
	RigOpNone     VfoOp = iota
	RigOpCpy      VfoOp = (1 << 0)
	RigOpXchg     VfoOp = (1 << 1)
	RigOpFromVfo  VfoOp = (1 << 2)
	RigOpToVfo    VfoOp = (1 << 3)
	RigOpMcl      VfoOp = (1 << 4)
	RigOpUp       VfoOp = (1 << 5)
	RigOpDown     VfoOp = (1 << 6)
	RigOpBandUp   VfoOp = (1 << 7)
	RigOpBandDown VfoOp = (1 << 8)
	RigOpLeft     VfoOp = (1 << 9)
	RigOpRight    VfoOp = (1 << 10)
	RigOpTune     VfoOp = (1 << 11)
	RigOpToggle   VfoOp = (1 << 12)
)

// Scan as declared in hamlib/rig.h:503
type Scan int32

// Scan enumeration from hamlib/rig.h:503
const (
	RigScanNone  Scan = iota
	RigScanMem   Scan = (1 << 0)
	RigScanSlct  Scan = (1 << 1)
	RigScanPrio  Scan = (1 << 2)
	RigScanProg  Scan = (1 << 3)
	RigScanDelta Scan = (1 << 4)
	RigScanVfo   Scan = (1 << 5)
	RigScanPlt   Scan = (1 << 6)
	RigScanStop  Scan = (1 << 7)
)

// Rmode as declared in hamlib/rig.h:817
type Rmode int32

// Rmode enumeration from hamlib/rig.h:817
const (
	RigModeNone     Rmode = iota
	RigModeAm       Rmode = (1 << 0)
	RigModeCw       Rmode = (1 << 1)
	RigModeUsb      Rmode = (1 << 2)
	RigModeLsb      Rmode = (1 << 3)
	RigModeRtty     Rmode = (1 << 4)
	RigModeFm       Rmode = (1 << 5)
	RigModeWfm      Rmode = (1 << 6)
	RigModeCwr      Rmode = (1 << 7)
	RigModeRttyr    Rmode = (1 << 8)
	RigModeAms      Rmode = (1 << 9)
	RigModePktlsb   Rmode = (1 << 10)
	RigModePktusb   Rmode = (1 << 11)
	RigModePktfm    Rmode = (1 << 12)
	RigModeEcssusb  Rmode = (1 << 13)
	RigModeEcsslsb  Rmode = (1 << 14)
	RigModeFax      Rmode = (1 << 15)
	RigModeSam      Rmode = (1 << 16)
	RigModeSal      Rmode = (1 << 17)
	RigModeSah      Rmode = (1 << 18)
	RigModeDsb      Rmode = (1 << 19)
	RigModeFmn      Rmode = (1 << 21)
	RigModeTestsMax Rmode = 2097153
)

// ChanType as declared in hamlib/rig.h:1037
type ChanType int32

// ChanType enumeration from hamlib/rig.h:1037
const (
	RigMtypeNone    ChanType = iota
	RigMtypeMem     ChanType = 1
	RigMtypeEdge    ChanType = 2
	RigMtypeCall    ChanType = 3
	RigMtypeMemopad ChanType = 4
	RigMtypeSat     ChanType = 5
	RigMtypeBand    ChanType = 6
	RigMtypePrio    ChanType = 7
)

// Version as declared in hamlib/rig.h:75
var Version string

// Copyright as declared in hamlib/rig.h:76
var Copyright string

// Version2 as declared in hamlib/rig.h:77
var Version2 string

// Copyright2 as declared in hamlib/rig.h:78
var Copyright2 string

// SerialParityE as declared in hamlib/rig.h:185
type SerialParityE int32

// SerialParityE enumeration from hamlib/rig.h:185
const (
	RigParityNone  = iota
	RigParityOdd   = 1
	RigParityEven  = 2
	RigParityMark  = 3
	RigParitySpace = 4
)

// SerialHandshakeE as declared in hamlib/rig.h:196
type SerialHandshakeE int32

// SerialHandshakeE enumeration from hamlib/rig.h:196
const (
	RigHandshakeNone     = iota
	RigHandshakeXonxoff  = 1
	RigHandshakeHardware = 2
)

// SerialControlStateE as declared in hamlib/rig.h:206
type SerialControlStateE int32

// SerialControlStateE enumeration from hamlib/rig.h:206
const (
	RigSignalUnset = iota
	RigSignalOn    = 1
	RigSignalOff   = 2
)

// AgcLevelE as declared in hamlib/rig.h:590
type AgcLevelE int32

// AgcLevelE enumeration from hamlib/rig.h:590
const (
	RigAgcOff       = iota
	RigAgcSuperfast = 1
	RigAgcFast      = 2
	RigAgcSlow      = 3
	RigAgcUser      = 4
	RigAgcMedium    = 5
	RigAgcAuto      = 6
)

// MeterLevelE as declared in hamlib/rig.h:603
type MeterLevelE int32

// MeterLevelE enumeration from hamlib/rig.h:603
const (
	RigMeterNone = iota
	RigMeterSwr  = (1 << 0)
	RigMeterComp = (1 << 1)
	RigMeterAlc  = (1 << 2)
	RigMeterIc   = (1 << 3)
	RigMeterDb   = (1 << 4)
	RigMeterPo   = (1 << 5)
	RigMeterVdd  = (1 << 6)
)
