// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 01 Feb 2017 05:13:32 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package hamlib provides Go bindings for Hamlib (radio control toolkit).
*/
package hamlib
