// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 01 Feb 2017 05:13:32 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

package hamlib

/*
#cgo pkg-config: hamlib
#include "hamlib/rig.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Rig as declared in hamlib/rig.h:136
type Rig C.RIG

// Value as declared in hamlib/rig.h:623
const sizeofValue = unsafe.Sizeof(C.value_t{})

type Value [sizeofValue]byte

// FreqRange as declared in hamlib/rig.h:844
type FreqRange struct {
	Start          float64
	End            float64
	Modes          Rmode
	LowPower       int32
	HighPower      int32
	Vfo            int32
	Ant            int32
	ref5a1ffb63    *C.freq_range_t
	allocs5a1ffb63 interface{}
}

// Chan as declared in hamlib/rig.h:1065
type Chan struct {
	Start          int32
	End            int32
	Type           ChanType
	ref3d786229    *C.chan_t
	allocs3d786229 interface{}
}

// ChanCb type as declared in hamlib/rig.h:1114
type ChanCb func(arg0 []Rig, arg1 [][]Channel, arg2 int32, arg3 []Chan, arg4 unsafe.Pointer) int32

// ConfvalCb type as declared in hamlib/rig.h:1115
type ConfvalCb func(arg0 []Rig, arg1 []Confparams, arg2 []Value, arg3 unsafe.Pointer) int32

// Port as declared in hamlib/rig.h:1395
type Port C.hamlib_port_t

// VprintfCb type as declared in hamlib/rig.h:1475
type VprintfCb func(arg0 RigDebugLevelE, arg1 unsafe.Pointer, arg2 string, arg3 unsafe.Pointer) int32

// FreqCb type as declared in hamlib/rig.h:1477
type FreqCb func(arg0 []Rig, arg1 int32, arg2 float64, arg3 unsafe.Pointer) int32

// ModeCb type as declared in hamlib/rig.h:1478
type ModeCb func(arg0 []Rig, arg1 int32, arg2 Rmode, arg3 int, arg4 unsafe.Pointer) int32

// VfoCb type as declared in hamlib/rig.h:1479
type VfoCb func(arg0 []Rig, arg1 int32, arg2 unsafe.Pointer) int32

// PttCb type as declared in hamlib/rig.h:1480
type PttCb func(arg0 []Rig, arg1 int32, arg2 Ptt, arg3 unsafe.Pointer) int32

// DcdCb type as declared in hamlib/rig.h:1481
type DcdCb func(arg0 []Rig, arg1 int32, arg2 Dcd, arg3 unsafe.Pointer) int32

// PltuneCb type as declared in hamlib/rig.h:1482
type PltuneCb func(arg0 []Rig, arg1 int32, arg2 []float64, arg3 []Rmode, arg4 []int, arg5 unsafe.Pointer) int32

// RigProbeFunc type as declared in hamlib/rig.h:1719
type RigProbeFunc func(arg0 *Port, arg1 RigModel, arg2 unsafe.Pointer) int32

// RigModel type as declared in hamlib/riglist.h:530
type RigModel int32

// Confparams as declared in hamlib/rig.h:539
type Confparams struct {
	Token          int
	Name           string
	Label          string
	Tooltip        string
	Dflt           string
	Type           RigConfE
	ref8d683b0d    *C.struct_confparams
	allocs8d683b0d interface{}
}

// RigCaps as declared in hamlib/rig.h:1135
type RigCaps C.struct_rig_caps

// Channel as declared in hamlib/rig.h:976
type Channel struct {
	ChannelNum     int32
	BankNum        int32
	Vfo            int32
	Ant            int32
	Freq           float64
	Mode           Rmode
	Width          int
	TxFreq         float64
	TxMode         Rmode
	TxWidth        int
	Split          Split
	TxVfo          int32
	RptrShift      RptrShift
	RptrOffs       int
	TuningStep     int
	Rit            int
	Xit            int
	Funcs          uint
	Levels         [32]Value
	CtcssTone      uint32
	CtcssSql       uint32
	DcsCode        uint32
	DcsSql         uint32
	ScanGroup      int32
	Flags          int32
	ChannelDesc    [30]byte
	ref9eaa335d    *C.channel_t
	allocs9eaa335d interface{}
}

// RigState as declared in hamlib/rig.h:131
type RigState C.struct_rig_state

// RigCallbacks as declared in hamlib/rig.h:1501
type RigCallbacks C.struct_rig_callbacks
